# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f8be9bfc31c630b02b3c620fecdebd78757ea499719efe8ffc6701ee2eb8fbe4559aed3e31ebf9b892391b5c6cb13b1e00e8b4bdf79d80c05dcae5ce4dc5b1f

test:
  secret_key_base: c266aac57c4852384ec7227318c27bcc556906a445adb64bede8e1deb05de5a2d6129a1b9a729d0628ff98d5e024fef9cfdbe3930de3e586ac51be138ff4fc9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
